// The list of claims shown on the grid.
//
// To add one, copy an entry and give it a unique `id` (it's what saved
// answers are keyed on, so don't rename an id once the site is live).
//   name:     short label on the card
//   category: one of the keys in CATEGORIES below
//   question: what the visitor answers Yes or No to
//   verdict:  one or two sentences on what the evidence says
//   link:     where to read more

const CATEGORIES = {
  divination: { label: "Divination & Psychics", icon: "🔮" },
  medicine: { label: "Alternative Medicine", icon: "💊" },
  newage: { label: "New Age & Energy", icon: "✨" },
  paranormal: { label: "Paranormal & Aliens", icon: "👽" },
  conspiracy: { label: "Conspiracies", icon: "🛸" },
  religion: { label: "Religion", icon: "⛪" },
};

const CLAIMS = [
  // Divination & Psychics
  {
    id: "astrology",
    name: "Astrology",
    category: "divination",
    question: "Do the positions of the planets when you were born shape your personality and future?",
    verdict: "Controlled tests, including a double-blind study published in Nature (Carlson, 1985), found astrologers do no better than chance at matching birth charts to personalities.",
    link: "https://en.wikipedia.org/wiki/Astrology_and_science",
  },
  {
    id: "mediums",
    name: "Mediums",
    category: "divination",
    question: "Can mediums talk to the dead and pass on their messages?",
    verdict: "Every controlled test has failed. Readings are explained by cold reading, hot reading and the Barnum effect.",
    link: "https://en.wikipedia.org/wiki/Mediumship",
  },
  {
    id: "psychics",
    name: "Psychics & ESP",
    category: "divination",
    question: "Can some people read minds or sense the future?",
    verdict: "A century of parapsychology has produced no replicable effect. James Randi's $1 million prize went unclaimed for 50 years.",
    link: "https://en.wikipedia.org/wiki/Extrasensory_perception",
  },
  {
    id: "tarot",
    name: "Tarot",
    category: "divination",
    question: "Can tarot cards reveal hidden truths about your life or future?",
    verdict: "Card draws are random; any insight comes from the reader and the client filling in vague meanings.",
    link: "https://en.wikipedia.org/wiki/Tarot_card_reading",
  },
  {
    id: "numerology",
    name: "Numerology",
    category: "divination",
    question: "Do numbers from your name or birthday have special power over your life?",
    verdict: "There is no mechanism and no evidence. Results depend entirely on which arbitrary letter-to-number system you pick.",
    link: "https://en.wikipedia.org/wiki/Numerology",
  },
  {
    id: "palmistry",
    name: "Palm Reading",
    category: "divination",
    question: "Can the lines on your palm predict your life?",
    verdict: "Palm lines are skin creases formed in the womb. Studies have found no link between them and lifespan or character.",
    link: "https://en.wikipedia.org/wiki/Palmistry",
  },
  {
    id: "ouija",
    name: "Ouija Boards",
    category: "divination",
    question: "Do spirits move the planchette on a Ouija board?",
    verdict: "The ideomotor effect: users move it with tiny unconscious muscle movements. Blindfold the players and the messages turn to gibberish.",
    link: "https://en.wikipedia.org/wiki/Ouija",
  },
  {
    id: "dowsing",
    name: "Dowsing",
    category: "divination",
    question: "Can a forked stick or bent rods find underground water or metal?",
    verdict: "In controlled trials such as the 1991 Kassel test, dowsers did no better than chance at finding hidden water pipes.",
    link: "https://en.wikipedia.org/wiki/Dowsing",
  },

  // Alternative Medicine
  {
    id: "homeopathy",
    name: "Homeopathy",
    category: "medicine",
    question: "Can water that 'remembers' a diluted substance cure illness?",
    verdict: "Most remedies are diluted past the point where a single molecule remains. Australia's NHMRC reviewed 1,800 studies and found it works no better than placebo for any condition.",
    link: "https://en.wikipedia.org/wiki/Homeopathy",
  },
  {
    id: "faith-healing",
    name: "Faith Healers",
    category: "medicine",
    question: "Can faith healers cure disease by laying on hands or prayer?",
    verdict: "No documented cures survive scrutiny. Peter Popoff was caught receiving 'divine' information through an earpiece from his wife.",
    link: "https://en.wikipedia.org/wiki/Faith_healing",
  },
  {
    id: "crystals",
    name: "Crystal Healing",
    category: "medicine",
    question: "Do crystals have healing energy?",
    verdict: "In a study by Christopher French, people holding fake crystals reported the same 'energy' as those holding real ones.",
    link: "https://en.wikipedia.org/wiki/Crystal_healing",
  },
  {
    id: "reiki",
    name: "Reiki",
    category: "medicine",
    question: "Can a practitioner heal you by channeling 'universal life energy' through their hands?",
    verdict: "Systematic reviews find no effect beyond placebo, and no 'life energy' field has ever been detected.",
    link: "https://en.wikipedia.org/wiki/Reiki",
  },
  {
    id: "therapeutic-touch",
    name: "Therapeutic Touch",
    category: "medicine",
    question: "Can practitioners feel and fix your 'energy field' without touching you?",
    verdict: "A 9-year-old's science fair test, published in JAMA in 1998, showed practitioners couldn't even tell which hand was near hers.",
    link: "https://en.wikipedia.org/wiki/Therapeutic_touch",
  },
  {
    id: "acupuncture",
    name: "Acupuncture",
    category: "medicine",
    question: "Do needles placed on 'meridians' unblock your qi and heal disease?",
    verdict: "Sham acupuncture (wrong spots, retractable needles) works just as well as the real thing. Meridians and qi have no anatomical basis.",
    link: "https://en.wikipedia.org/wiki/Acupuncture",
  },
  {
    id: "chiropractic",
    name: "Chiropractic Subluxations",
    category: "medicine",
    question: "Are most diseases caused by misaligned spines that a chiropractor can fix?",
    verdict: "'Subluxations' have never been shown to exist or cause disease. Neck manipulation carries a small risk of stroke.",
    link: "https://en.wikipedia.org/wiki/Vertebral_subluxation",
  },
  {
    id: "naturopathy",
    name: "Naturopathy",
    category: "medicine",
    question: "Can 'natural' remedies replace evidence-based medicine?",
    verdict: "Naturopathy bundles many unproven practices; 'natural' isn't the same as effective or safe.",
    link: "https://en.wikipedia.org/wiki/Naturopathy",
  },
  {
    id: "detox",
    name: "Detox Cleanses",
    category: "medicine",
    question: "Do juice cleanses, foot pads or colon cleanses flush 'toxins' from your body?",
    verdict: "Your liver and kidneys already do this. Detox products never name which toxins they remove, and the foot pads turn brown from sweat.",
    link: "https://en.wikipedia.org/wiki/Detoxification_(alternative_medicine)",
  },
  {
    id: "reflexology",
    name: "Reflexology",
    category: "medicine",
    question: "Does each part of your foot connect to an organ you can heal by massaging it?",
    verdict: "There's no nerve map linking feet to organs, and reflexologists' charts don't even agree with each other.",
    link: "https://en.wikipedia.org/wiki/Reflexology",
  },
  {
    id: "iridology",
    name: "Iridology",
    category: "medicine",
    question: "Can patterns in your iris diagnose disease elsewhere in your body?",
    verdict: "In blinded tests iridologists fail to identify known illnesses, and give different diagnoses for the same eye.",
    link: "https://en.wikipedia.org/wiki/Iridology",
  },
  {
    id: "essential-oils",
    name: "Essential Oil Cures",
    category: "medicine",
    question: "Can essential oils cure serious illnesses?",
    verdict: "They can smell nice. The FDA has warned sellers for claiming they treat cancer, Ebola and COVID-19.",
    link: "https://en.wikipedia.org/wiki/Aromatherapy",
  },
  {
    id: "magnets",
    name: "Magnet Therapy",
    category: "medicine",
    question: "Do magnetic bracelets or insoles relieve pain and improve health?",
    verdict: "Randomized trials show no benefit beyond placebo. The magnets are too weak to affect blood or tissue.",
    link: "https://en.wikipedia.org/wiki/Magnet_therapy",
  },
  {
    id: "anti-vax",
    name: "Vaccines Cause Autism",
    category: "medicine",
    question: "Do vaccines cause autism?",
    verdict: "The 1998 study behind this was fraudulent and retracted. Studies of millions of children find no link.",
    link: "https://en.wikipedia.org/wiki/Vaccines_and_autism",
  },

  // New Age & Energy
  {
    id: "chakras",
    name: "Chakras",
    category: "newage",
    question: "Does your body have spinning energy centers that affect your health?",
    verdict: "No anatomical or physical evidence of chakras exists. Different traditions don't even agree on how many there are.",
    link: "https://en.wikipedia.org/wiki/Chakra",
  },
  {
    id: "auras",
    name: "Auras",
    category: "newage",
    question: "Do people give off colored auras that some can see?",
    verdict: "Aura readers fail blinded tests. 'Aura photography' just shows heat and moisture on the skin.",
    link: "https://en.wikipedia.org/wiki/Aura_(paranormal)",
  },
  {
    id: "law-of-attraction",
    name: "Law of Attraction",
    category: "newage",
    question: "Can you get what you want just by thinking positively about it?",
    verdict: "Thoughts don't emit attracting 'vibrations'. Research suggests fantasizing about success can actually make people less likely to achieve it.",
    link: "https://en.wikipedia.org/wiki/Law_of_attraction_(New_Thought)",
  },
  {
    id: "reincarnation",
    name: "Past-Life Regression",
    category: "newage",
    question: "Can hypnosis uncover memories of your past lives?",
    verdict: "Hypnosis makes people more suggestible, not more accurate. 'Past lives' tend to be famous people and historically wrong.",
    link: "https://en.wikipedia.org/wiki/Past_life_regression",
  },
  {
    id: "orgone",
    name: "Orgone & Energy Devices",
    category: "newage",
    question: "Can pyramids, orgonite or 'energy' gadgets block bad energy or recharge you?",
    verdict: "These 'energies' have never been detected by any instrument. The devices are resin, metal shavings and marketing.",
    link: "https://en.wikipedia.org/wiki/Orgone",
  },

  // Paranormal & Aliens
  {
    id: "alien-abduction",
    name: "Alien Abduction",
    category: "paranormal",
    question: "Are aliens abducting people and experimenting on them?",
    verdict: "Abduction stories fit sleep paralysis, hypnagogic dreams and memories created under hypnosis. No physical evidence has ever been produced.",
    link: "https://en.wikipedia.org/wiki/Alien_abduction_claimants",
  },
  {
    id: "ancient-aliens",
    name: "Ancient Aliens",
    category: "paranormal",
    question: "Did aliens help build the pyramids and other ancient wonders?",
    verdict: "Archaeologists have found the Egyptian workers' villages, tools, quarries and even their time sheets.",
    link: "https://en.wikipedia.org/wiki/Ancient_astronauts",
  },
  {
    id: "ufo-coverup",
    name: "UFO Cover-ups",
    category: "paranormal",
    question: "Is the government hiding crashed alien spacecraft and bodies?",
    verdict: "Roswell was a Project Mogul balloon. Decades of investigations have turned up no alien hardware or bodies.",
    link: "https://en.wikipedia.org/wiki/Roswell_incident",
  },
  {
    id: "ghosts",
    name: "Ghosts",
    category: "paranormal",
    question: "Do the spirits of the dead haunt places?",
    verdict: "Ghost hunting has never produced verifiable evidence. Sightings are explained by infrasound, carbon monoxide, pareidolia and suggestion.",
    link: "https://en.wikipedia.org/wiki/Ghost",
  },
  {
    id: "bigfoot",
    name: "Bigfoot",
    category: "paranormal",
    question: "Is a giant ape-man roaming North American forests?",
    verdict: "No body, bones or verified DNA, despite millions of trail cameras. Several famous footprints and films were admitted hoaxes.",
    link: "https://en.wikipedia.org/wiki/Bigfoot",
  },
  {
    id: "loch-ness",
    name: "Loch Ness Monster",
    category: "paranormal",
    question: "Does a prehistoric monster live in Loch Ness?",
    verdict: "A 2018 environmental DNA survey of the whole loch found no reptile DNA, but plenty of eels. The famous 1934 photo was a toy submarine.",
    link: "https://en.wikipedia.org/wiki/Loch_Ness_Monster",
  },
  {
    id: "bermuda-triangle",
    name: "Bermuda Triangle",
    category: "paranormal",
    question: "Do ships and planes mysteriously vanish in the Bermuda Triangle?",
    verdict: "Insurers and the US Coast Guard find no higher loss rate there than any other busy stretch of ocean.",
    link: "https://en.wikipedia.org/wiki/Bermuda_Triangle",
  },

  // Conspiracies
  {
    id: "flat-earth",
    name: "Flat Earth",
    category: "conspiracy",
    question: "Is the Earth flat?",
    verdict: "Known since Eratosthenes measured it around 240 BC. Ships vanish hull-first over the horizon, and you can watch a round shadow on the Moon during an eclipse.",
    link: "https://en.wikipedia.org/wiki/Flat_Earth",
  },
  {
    id: "moon-hoax",
    name: "Moon Landing Hoax",
    category: "conspiracy",
    question: "Were the Moon landings faked?",
    verdict: "Retroreflectors left on the Moon are still used by observatories today, and orbiters have photographed the landing sites.",
    link: "https://en.wikipedia.org/wiki/Moon_landing_conspiracy_theories",
  },
  {
    id: "chemtrails",
    name: "Chemtrails",
    category: "conspiracy",
    question: "Are plane contrails secretly spraying chemicals on the public?",
    verdict: "Contrails are condensed water vapor. In a survey of 77 atmospheric scientists, 76 found no evidence of a secret spraying program.",
    link: "https://en.wikipedia.org/wiki/Chemtrail_conspiracy_theory",
  },
  {
    id: "5g",
    name: "5G Harms",
    category: "conspiracy",
    question: "Do 5G cell towers make people sick or spread viruses?",
    verdict: "5G radio waves are non-ionizing and far below safety limits. Viruses can't travel on radio waves.",
    link: "https://en.wikipedia.org/wiki/5G_misinformation",
  },
  {
    id: "lizard-people",
    name: "Reptilian Elite",
    category: "conspiracy",
    question: "Are world leaders secretly shape-shifting lizard people?",
    verdict: "No. This one comes from David Icke and recycles older antisemitic conspiracy myths.",
    link: "https://en.wikipedia.org/wiki/Reptilian_conspiracy_theory",
  },

  // Religion
  {
    id: "mormonism",
    name: "Mormonism",
    category: "religion",
    question: "Did Joseph Smith translate golden plates, left by ancient American civilizations, through a seer stone in a hat?",
    verdict: "No plates were ever produced for inspection. Archaeology and DNA studies find no trace of the Book of Mormon's Israelite civilizations in the Americas.",
    link: "https://en.wikipedia.org/wiki/Archaeology_and_the_Book_of_Mormon",
  },
  {
    id: "scientology",
    name: "Scientology",
    category: "religion",
    question: "Are we haunted by the spirits of aliens killed by the galactic overlord Xenu 75 million years ago?",
    verdict: "L. Ron Hubbard was a science fiction writer. The 'E-meter' used in auditing is a simple skin-resistance meter.",
    link: "https://en.wikipedia.org/wiki/Xenu",
  },
  {
    id: "catholicism",
    name: "Catholicism",
    category: "religion",
    question: "Do bread and wine literally become the body and blood of Christ during Mass?",
    verdict: "After consecration, the bread and wine remain chemically bread and wine; the doctrine says only their unobservable 'substance' changes.",
    link: "https://en.wikipedia.org/wiki/Transubstantiation",
  },
  {
    id: "lutheranism",
    name: "Lutheranism",
    category: "religion",
    question: "Is Christ's body truly present 'in, with and under' the bread and wine of communion?",
    verdict: "Like transubstantiation, the claim is defined so that it can't be observed or tested.",
    link: "https://en.wikipedia.org/wiki/Sacramental_union",
  },
  {
    id: "methodism",
    name: "Methodism",
    category: "religion",
    question: "Can the Holy Spirit make you perfect in love during this life, as John Wesley taught?",
    verdict: "A supernatural claim with no testable evidence behind it.",
    link: "https://en.wikipedia.org/wiki/Christian_perfection",
  },
  {
    id: "young-earth",
    name: "Young Earth Creationism",
    category: "religion",
    question: "Was the Earth created less than 10,000 years ago?",
    verdict: "Radiometric dating, ice cores, tree rings and starlight from billions of light-years away all show a universe billions of years old.",
    link: "https://en.wikipedia.org/wiki/Young_Earth_creationism",
  },
  {
    id: "noahs-flood",
    name: "Noah's Flood",
    category: "religion",
    question: "Did a worldwide flood cover every mountain, with all land animals saved on one boat?",
    verdict: "There is no global flood layer in the geological record, and an ark couldn't hold, feed or ventilate millions of species.",
    link: "https://en.wikipedia.org/wiki/Flood_geology",
  },
  {
    id: "jehovahs-witnesses",
    name: "Jehovah's Witnesses",
    category: "religion",
    question: "Is the end of the world coming soon, as the Watch Tower Society predicts?",
    verdict: "The movement has predicted or strongly implied the end for 1914, 1925 and 1975. It didn't come.",
    link: "https://en.wikipedia.org/wiki/Eschatology_of_Jehovah%27s_Witnesses",
  },
  {
    id: "christian-science",
    name: "Christian Science",
    category: "religion",
    question: "Is illness an illusion that prayer can heal instead of medicine?",
    verdict: "Studies of Christian Scientist graduates found higher death rates than comparable groups, and children have died from untreated, treatable illnesses.",
    link: "https://en.wikipedia.org/wiki/Christian_Science",
  },
  {
    id: "prosperity-gospel",
    name: "Prosperity Gospel",
    category: "religion",
    question: "Will God make you rich if you give money to a preacher?",
    verdict: "The reliable result is that the preachers get rich. Several have bought private jets with donations.",
    link: "https://en.wikipedia.org/wiki/Prosperity_theology",
  },
  {
    id: "rapture",
    name: "The Rapture",
    category: "religion",
    question: "Will believers soon be lifted bodily into the sky while everyone else is left behind?",
    verdict: "The idea dates from John Nelson Darby in the 1830s, and every date predicted for it so far has passed.",
    link: "https://en.wikipedia.org/wiki/Rapture",
  },
  {
    id: "exorcism",
    name: "Demonic Possession",
    category: "religion",
    question: "Can demons possess people and be driven out by exorcism?",
    verdict: "Reported possessions match known conditions like epilepsy, schizophrenia and dissociative disorders. Exorcisms have killed people.",
    link: "https://en.wikipedia.org/wiki/Spirit_possession",
  },
];
